# Generated by Django 5.2.1 on 2025-07-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billreminder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='billreminder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='billreminder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='billreminder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='billreminder',
            name='recurrence',
        ),
    ]
