# Generated by Django 5.2.1 on 2025-07-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses', to='budgeting.budgetgroup'),
        ),
    ]
