# Generated by Django 5.2.1 on 2025-06-21 11:33

import django.contrib.postgres.fields
import django.db.models.deletion
import goals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.TextField()),
                ('deadline', models.DateTimeField(default=goals.models.default_deadline)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_progress', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_actions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
