# Generated by Django 5.2.1 on 2025-06-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='recommended_actions',
        ),
    ]
